-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'MANAGER_REQUEST_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE 'MANAGER_REQUEST_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'MANAGER_REQUEST_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'MANAGER_REQUEST_EXPIRED';
